add literals and ops, cause a crash
env RUST_BACKTRACE=full tree-sitter test
  syntax:
    ✓ boolean variable
    ✓ numeric literals
    ✗ expressions

1 failure:

expected / actual

  1. expressions:
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/src/test.rs:299:45
stack backtrace:
   0:     0x564b0206ff36 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1ef07120adb99796
   1:     0x564b020891ec - core::fmt::write::h59cc4b3dea155cce
   2:     0x564b02056ae5 - std::io::Write::write_fmt::he7e4fb4b70c5207a
   3:     0x564b02065710 - std::panicking::default_hook::{{closure}}::h67c88fba3a1757d9
   4:     0x564b020652b1 - std::panicking::default_hook::had51536d17f32530
   5:     0x564b02065cc3 - std::panicking::rust_panic_with_hook::hcdfd560c4f6afa56
   6:     0x564b020703f2 - std::panicking::begin_panic_handler::{{closure}}::h5e7abb77afe4762c
   7:     0x564b02070084 - std::sys_common::backtrace::__rust_end_short_backtrace::hb15a1d01c910931c
   8:     0x564b02065802 - rust_begin_unwind
   9:     0x564b01d65581 - core::panicking::panic_fmt::h4b7f7457475b4299
  10:     0x564b01d654cd - core::panicking::panic::hf2a1a8726f570f0d
  11:     0x564b01daac63 - tree_sitter_cli::test::format_sexp_indented::hcc7ee80218661f6e
  12:     0x564b01da74b6 - tree_sitter_cli::test::run_tests_at_path::h8afce80b710b8f29
  13:     0x564b01d72d86 - tree_sitter::run::hc0169a5f27ccdf2c
  14:     0x564b01d6ebbc - tree_sitter::main::h347d6a951c582430
  15:     0x564b01d68153 - std::sys_common::backtrace::__rust_begin_short_backtrace::he2e512df5c180cb0
  16:     0x564b01d800c9 - std::rt::lang_start::{{closure}}::hca8bb04d700c840f
  17:     0x564b02068191 - std::rt::lang_start_internal::hc2cb966a7a4d713d
  18:     0x564b01d77172 - main
  19:     0x7f4767aed780 - __libc_start_main
  20:     0x564b01d658aa - _start
  21:                0x0 - <unknown>